@echo off
cd /d C:\ArtisticDentalPortal

REM --- Run pipeline ---
py pipeline.py
if errorlevel 1 (
    echo [%date% %time%] WARNING: pipeline.py exited with error - skipping git push
    exit /b 1
)

REM --- Check if cache/latest/ actually changed ---
git add cache/latest/
git diff --cached --quiet
if errorlevel 1 (
    REM Data changed — stamp _data_version.py to trigger Streamlit Cloud redeploy
    echo # Auto-generated by run_pipeline.bat - do not edit manually. > _data_version.py
    echo # Changing this file forces Streamlit Cloud to redeploy with fresh CSV data. >> _data_version.py
    echo DATA_VERSION = "%date% %time%" >> _data_version.py
    git add _data_version.py
    git commit -m "Pipeline data update %date% %time%"
    git push origin main
    echo [%date% %time%] Data changed - pushed to GitHub.
) else (
    REM No data change — skip push, no Streamlit redeploy
    echo [%date% %time%] No data changes - skipping push.
)
