@echo off
cd /d C:\ArtisticDentalPortal

REM --- Never let git block on a credential prompt. This runs unattended; a
REM --- failed credential store once left git sitting at "Username for
REM --- 'https://github.com':" forever, wedging the scheduled task. With these
REM --- set, an auth failure returns an error immediately instead of hanging.
set GIT_TERMINAL_PROMPT=0
set GCM_INTERACTIVE=never
set GIT_ASKPASS=
set SSH_ASKPASS=

REM --- Self-heal any git ref corruption left by an interrupted push ---
py -c "from git_health import repair_if_broken; from pathlib import Path; repair_if_broken(Path('.'))"

REM --- Run pipeline ---
py pipeline.py
if errorlevel 1 (
    echo [%date% %time%] WARNING: pipeline.py exited with error - skipping git push
    exit /b 1
)

REM --- Run production pipeline (GM Summary + Fixed/Removable dashboards) ---
py production_pipeline.py
if errorlevel 1 (
    echo [%date% %time%] WARNING: production_pipeline.py exited with error - production dashboards may show stale data
)

REM --- Check if cache/latest/ actually changed ---
git add cache/latest/ assets/production_dashboard_live.html
git diff --cached --quiet
if errorlevel 1 (
    REM Data changed — stamp _data_version.py to trigger Streamlit Cloud redeploy
    echo # Auto-generated by run_pipeline.bat - do not edit manually. > _data_version.py
    echo # Changing this file forces Streamlit Cloud to redeploy with fresh CSV data. >> _data_version.py
    echo DATA_VERSION = "%date% %time%" >> _data_version.py
    git add _data_version.py
    git commit -m "Pipeline data update %date% %time%"
    git push origin main
    echo [%date% %time%] Data changed - pushed to GitHub.
) else (
    REM No data change — skip push, no Streamlit redeploy
    echo [%date% %time%] No data changes - skipping push.
)
